### ISSUE TITLE
Satisfactory U7 Experimantal

### ISSUE THREAD

**Issue by gamenTV** [ChrisViral/AutoSplittersContinued#8]
Sadly the mod is broken in U7 Experimantal. Got this "error" message:

Plugin 'AutoSplittersContinued' failed to load because module 'AutoSplittersContinued' could not be loaded. There may be an operation system error or the module may not b e properly set up.

**Comment by ChrisViral** [comment]
I do not support experimental releases. An update for early access will come out shortly.
